# Generated by Django 3.1 on 2021-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('SFname', models.CharField(default='First Name', max_length=100)),
                ('SLname', models.CharField(default='Last Name', max_length=100)),
                ('SEmail', models.CharField(default='Email Name', max_length=100)),
                ('SUsername', models.CharField(default='Username ', max_length=100)),
                ('SPassword', models.TextField(default='Password ', max_length=3000)),
                ('SContactNo', models.CharField(default='Contact no', max_length=100)),
                ('SProfile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
