# Generated by Django 3.1 on 2021-03-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('EventTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('EventType', models.CharField(default='', max_length=255)),
                ('Super_AdminAccount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.super_adminaccount')),
            ],
        ),
    ]
