# Generated by Django 3.1 on 2021-03-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(default='', max_length=255)),
                ('Cost', models.FloatField(default=0.0)),
                ('Registration_start', models.DateField()),
                ('Registration_end', models.DateField()),
                ('Runner_quantity', models.IntegerField(default=0)),
                ('Event_logo', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='Eventlogo/')),
                ('Status', models.CharField(default='', max_length=50)),
                ('EventTypeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event_type')),
            ],
        ),
    ]
