# Generated by Django 3.1 on 2021-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Surname', models.CharField(default='', max_length=255)),
                ('Ci', models.CharField(default='', max_length=255)),
                ('Ruc', models.CharField(default='', max_length=255)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Phones', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Direction', models.CharField(default='', max_length=255)),
                ('Nrocasa', models.IntegerField(default=0)),
                ('Birth_date', models.DateField()),
                ('Creation', models.DateTimeField(auto_now_add=True)),
                ('Password', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
