# Generated by Django 3.1 on 2021-03-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Event_Registration',
            fields=[
                ('Registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(default='', max_length=255)),
                ('Ruc', models.CharField(default='', max_length=255)),
                ('Payment_form', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('EventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
    ]
