# Generated by Django 3.1 on 2021-03-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_user_event_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('TypeOrder', models.CharField(default='', max_length=255)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('hash', models.CharField(default='', max_length=255)),
                ('MaxDateForPayment', models.CharField(default='', max_length=255)),
                ('Description', models.CharField(default='', max_length=255)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
    ]
