# Generated by Django 3.1 on 2021-03-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('weather', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('image_time', models.CharField(default='', max_length=255)),
                ('image_activity', models.CharField(default='', max_length=255)),
                ('mood_state', models.CharField(default='', max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('EventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
    ]
