# Generated by Django 3.1.5 on 2021-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210407_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
