# Generated by Django 3.1.5 on 2021-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='City',
            field=models.CharField(default='', max_length=255),
        ),
    ]
