# Generated by Django 3.1.5 on 2021-04-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_user_signup_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('weather', models.CharField(default='', max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.FloatField(default=0.0)),
                ('running_point', models.IntegerField(default=0)),
                ('EventId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.user_signup')),
            ],
        ),
        migrations.DeleteModel(
            name='time_progress',
        ),
    ]
