# Generated by Django 3.1.5 on 2021-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210416_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
