# Generated by Django 3.1.5 on 2021-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='contact_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
