# Generated by Django 3.1.5 on 2021-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_contact_us_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_title', models.CharField(max_length=100)),
                ('website_description', models.CharField(max_length=256)),
                ('website_logo', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='Eventlogo/')),
            ],
        ),
    ]
