# Generated by Django 3.1.5 on 2021-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_first_word', models.CharField(max_length=100)),
                ('slider_second_word', models.CharField(max_length=100)),
                ('slider_description', models.CharField(max_length=256)),
                ('slider_thumb', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/')),
            ],
        ),
    ]
