# Generated by Django 3.1.5 on 2021-04-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_progress',
            name='weather',
        ),
        migrations.AddField(
            model_name='event_progress',
            name='meter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
