# Generated by Django 3.1.5 on 2021-04-27 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_event_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_thumb',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_description',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_first_word',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_second_word',
            new_name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='button_name',
            field=models.CharField(default=datetime.datetime(2021, 4, 27, 12, 23, 49, 674624, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='front_img',
            field=models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/'),
        ),
    ]
