# Generated by Django 3.1.5 on 2021-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210427_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='front_img_two',
            field=models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='slider/'),
        ),
    ]
