# Generated by Django 3.1.5 on 2021-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_slider_front_img_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_progress',
            name='meter',
            field=models.FloatField(default=0, null=True),
        ),
    ]
