# Generated by Django 3.1.5 on 2021-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20210510_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buy_link',
            field=models.FloatField(default=''),
        ),
    ]
