# Generated by Django 3.1.5 on 2021-05-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20210515_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='buy_link',
            new_name='distance',
        ),
    ]
