# Generated by Django 3.1.5 on 2021-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20210516_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='Token',
            field=models.CharField(default='', max_length=40),
        ),
    ]
